# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-20 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_tv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Show',
        ),
    ]
